account/urls.py
from django.urls import path
from account.views import (
home, 
login_view, 
register_view, 
logout_view, 
# profile_view,
edit_account_view,
)

app_name = "account"

urlpatterns = [
    path('', home, name='home'),
    path('login/', login_view, name="login"),
    path('register/', register_view, name="register"),
    path('logout/', logout_view, name='logout'),
    # path('<user_id>/profile/', profile_view, name='profile'),
    path('<user_id>/profile/', edit_account_view, name='profile')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from azbankgateways.urls import az_bank_gateways_urls
from product.bank import go_to_gateway_view, callback_gateway_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('product/', include('product.urls')),


    # bankgetways urls
    path('bankgateways/', az_bank_gateways_urls()),
    path('go-to-gateway/', go_to_gateway_view, name='go-to-gateway'),
    path('callback-gateway/', callback_gateway_view),


    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'),
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'),
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset/password_reset_confirm.html'), name='password_reset_confirm'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset/password_reset_form.html'), name='password_reset'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
     name='password_reset_complete'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/password_reset/password_change.html
{% extends 'account/base_profile.html' %}

{% block profile_content %}
<h6>Change Password</h6>
<hr>
<div class="style-form">
    <form method="post">
        {% csrf_token %}     
        <div class="form-group">
          <input name="old_password" placeholder="Old password" type="password" required="true">
        </div>
        <div class="form-group">
          <input name="new_password1" placeholder="New password" type="password" required="true">
        </div>
        <div class="form-group">
          <input name="new_password2" placeholder="Confirm password" type="password" required="true">
        </div>
        <div class="form-group">
          <button type="submit" class="btn btn-primary">Update</button>
      </div>    
    </form>
</div>

{% endblock %}

templates/password_reset/password_change_done.html
{% extends 'account/base_profile.html' %}

{% block profile_content %}
<h6>Change Password</h6>
<hr>

<div class="container">
	<div class="d-flex flex-column mb-5">
		<p class="m-auto">Your password has been Updated.</p>
	</div>
</div>

{% endblock %}

templates/password_reset/password_reset_complete.html
{% extends 'base.html' %}


{% block content %}

<div class="container">
	<div class="d-flex flex-column mb-5">
		<p class="m-auto">Your password has been changed successfully. You may go ahead and <a href="{% url 'account:login' %}">sign in</a> now.</p>
	</div>
</div>

{% endblock %}

templates/password_reset/password_reset_confirm.html
{% extends 'account/base_profile.html' %}

{% block content %}
<div class="style-form">
  {% if validlink%}
    <form method="post">
        {% csrf_token %}
        <h2 class="text-center">Change Password</h2>       
        <div class="form-group">
          <input name="new_password1" placeholder="New Password" type="password" required="true" >
        </div>
        <div class="form-group">
          <input name="new_password2" placeholder="Confirm Password" type="password" required="true" >
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Change Password</button>
        </div>        
    </form>
  {% else %}
    <p>
      The password reset link was invalid, possibly because it has already been used.
      Please request a new password reset.
    </p>
  {% endif %}
</div>
{% endblock %}

templates/password_reset/password_reset_done.html
{% extends 'base.html' %}

{% block content %}

<div class="container">

	<div class="d-flex flex-column">
		  <p class="m-auto p-2">
		    We've emailed you instructions for setting your password, if an account exists with the email you entered.
		    You should receive them shortly.
		  </p>
		  <p class="m-auto p-2">
		    If you don't receive an email, please make sure you've entered the address you registered with,
		    and check your spam folder.
		  </p>
		  <p class="m-auto p-2"><a href="{% url 'account:home' %}">Return to home page</a></p>
	</div>
</div>

{% endblock %}

templates/password_reset/password_reset_email.html
{% autoescape off %}
To initiate the password reset process for your Account {{ user.email }},
click the link below:

{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Thanks
Rabinweb
{% endautoescape %}

templates/password_reset/password_reset_form.html
{% extends 'account/base_profile.html' %}

{% block content %}
<div class="style-form">
    <form method="post">
        {% csrf_token %}
        <h2 class="text-center">Reset Password</h2>       
        <div class="form-group">
          <input name="email" placeholder="Email address" type="email" required="true" >
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Send reset email</button>
        </div>        
    </form>
</div>

{% endblock %}