mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from azbankgateways.urls import az_bank_gateways_urls
from product.bank import go_to_gateway_view, callback_gateway_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('product/', include('product.urls')),


    # bankgetways urls
    path('bankgateways/', az_bank_gateways_urls()),
    path('go-to-gateway/', go_to_gateway_view, name='go-to-gateway'),
    path('callback-gateway/', callback_gateway_view),


    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'),
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'),
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset/password_reset_confirm.html'), name='password_reset_confirm'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset/password_reset_form.html'), name='password_reset'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
     name='password_reset_complete'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from .views import view_product, product_detail, add_to_cart, checkout, update_cart


app_name = 'product'

urlpatterns = [
    path('', view_product, name='products'),
    path('product_detail/<int:prod_id>/', product_detail, name='product_detail'),
    path('add-to-cart/', add_to_cart, name='add-to-cart'),
    path('checkout/', checkout, name="checkout"),
    path('update-cart/', update_cart, name='update-cart')
]

product/models.py
from django.db import models
from account.models import Account



class Category(models.Model):
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=150, unique=True)


    def __str__(self):
        return self.title


def get_product_image_filepath(self, filename):
    return 'product/product_images/' + str(self.pk) + '/product_image.png'


def get_default_product_image():
    return "product/product_default_images/default_product_image.png"


class Product(models.Model):
    title = models.CharField(max_length=150, unique=True) 
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField(blank=True, null=True)
    quantity = models.IntegerField(null=False, blank=False)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=get_product_image_filepath, default=get_default_product_image, blank=True, null=True)

    def __str__(self):
        return self.title

    
    # Model Save override for upload image
    def save(self, *args, **kwargs):
        if self.id is None:
            saved_image = self.image
            self.image = None
            super(Product, self).save(*args, **kwargs)
            self.image = saved_image
            if 'force_insert' in kwargs:
                kwargs.pop('force_insert')

        super(Product, self).save(*args, **kwargs)


class Order(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    payment = models.ForeignKey('Payment', on_delete=models.SET_NULL, blank=True, null=True)
    total_price = models.FloatField(blank=True, null=True)
    date_order = models.DateTimeField(auto_now_add=True)
    tracking_code = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.user.username


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    order_at = models.DateTimeField(auto_now_add=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)

    def __str__(self):
        return self.product.title


class Cart(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.title



class Payment(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    payment_number = models.CharField(max_length=100)
    payment_method = models.CharField(max_length=100)
    amount_paid = models.CharField(max_length=100)
    status = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.payment_number

product/views.py
from django.shortcuts import render, redirect
from .models import Product, Cart
from django.http import JsonResponse
import json



def view_product(request):
    context = {}
    products = Product.objects.all()

    context['products'] = products

    return render(request, 'product/products.html', context)



def product_detail(request, prod_id):
    context = {}
    product = Product.objects.get(id=prod_id)

    context['product'] = product

    return render(request, 'product/product_detail.html', context)



def add_to_cart(request):
    current_user = request.user
    if request.method == "POST":
        if request.user.is_authenticated:
            product_id = int(request.POST.get('product_id'))
            
            product_check = Product.objects.get(id=product_id)
            if product_check:
                if Cart.objects.filter(user=current_user, product_id=product_id):
                    return JsonResponse({'status': 'Product is Already in Cart'})
                else:
                    product_qyt = 1
                    Cart.objects.create(user=current_user, product_id=product_id, quantity=product_qyt)
                    return JsonResponse({'status': 'Product added successfuly'})
            else:
                return JsonResponse({'status': 'No such Product found'})
        else:
            return JsonResponse({'status': "Login to continue"})
    return redirect('/')



def checkout(request):
    context = {}
    cart_items = Cart.objects.filter(user=request.user)

    context['cart_items'] = cart_items
    context['cart_total'] = cart_items.count()

    cart_total = 0
    total_price = 0
    if cart_items:
        for item in cart_items:
            total_price += (item.product.price) * item.quantity
            cart_total += item.quantity

        context['total_price'] = total_price
        context['cart_total'] = cart_total
    
    return render(request, 'product/checkout.html', context)



def update_cart(requset):
    data = json.loads(requset.body)
    prod_id = data['productId']
    action = data['action']

    cart_item = Cart.objects.filter(user=requset.user, product_id=prod_id)[0]


    if cart_item:
        if action == 'add':
            cart_item.quantity += 1
        elif action == 'remove':
            cart_item.quantity -= 1
        
        cart_item.save()

        if cart_item.quantity == 0:
            cart_item.delete()

    return JsonResponse({'status':"Update Successfully"})
    

templates/product/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>Checkout</h1>
<main class="page">
    <section class="shopping-cart dark">
        <div class="container-shopping-cart">
            <div class="content">
                <div class="row">
                    <div class="col-md-12 col-lg-8">
                        <div class="items">

                            {% for item in cart_items %}
                                <div class="product">
                                    <div class="row product_data">
                                        <div class="col-md-3">
                                            <img class="img-fluid mx-auto d-block image" src="{{ item.product.image.url }}">
                                        </div>
                                        <div class="col-md-8">
                                            <div class="info">
                                                <div class="row">
                                                    <div class="col-md-5 product-name">
                                                        <div class="product-name">
                                                            <a href="{% url 'product:product_detail' prod_id=item.product.id %}">{{ item.product.title }}</a>
                                                            {% comment %} <div class="product-info">
                                                                <div>Display: <span class="value">5 inch</span></div>
                                                                <div>RAM: <span class="value">4GB</span></div>
                                                                <div>Memory: <span class="value">32GB</span></div>
                                                            </div> {% endcomment %}
                                                        </div>
                                                    </div>
                                                    <input type='hidden' class='prod_id' value="{{ item.product.id }}">
                                                        {% csrf_token %}

                                                        {% if item.product.quantity >= item.quantity %}
                                                        <div class="col-md-4 quantity">
                                                            
                                                            <label for="quantity">Quantity:{{ item.quantity }}</label>

                                                            <div class="input-group text-center mb-3">

                                                                <button class="input-group-text changeQuantity update-cart" data-action="remove" data-product="{{ item.product.id }}">-</button>
                                                            
                                                                <input type="text" name="quantity" class="form-control qty-input text-center" value="{{ item.quantity }}">
    
                                                                <button class="input-group-text changeQuantity update-cart" data-action="add" data-product="{{ item.product.id }}">+</button>

                                                            </div>

                                                            {% else %}
                                                                <h6>Out of Stock</h6>
                                                            {% endif %}

                                                        </div>


                                                    <div class="col-md-3 price">
                                                        <span>${{ item.product.price }}</span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                
                            {% endfor %}

                        </div>
                    </div>
                    <div class="col-md-12 col-lg-4">
                        <div class="summary">
                            <h3>Summary</h3>
                            <div class="summary-item"><span class="text">Cart Total</span><span class="price">{{ cart_total }}</span></div>
                            <div class="summary-item"><span class="text">Total</span><span class="price">${{total_price}}</span></div>
                            <a href="{% url 'go-to-gateway' %}" class="btn btn-primary btn-lg btn-block">Checkout</a>
                        </div>
                    </div>
                </div> 
            </div>
        </div>
    </section>
</main>

<script src="{% static 'main/js/cart.js' %}" type="text/javascript"></script>
{% endblock %}

templates/product/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>Product</h1>
<div class="container">
    <div class="card product_data">
        <div class="card-body">
            <h3 class="card-title">{{ product.title }}</h3>
            <div class="row">
                <div class="col-lg-5 col-md-5 col-sm-6">
                    <div class="white-box text-center"><img src="{{ product.image.url }}" class="img-product"></div>
                </div>
                <div class="col-lg-7 col-md-7 col-sm-6">
                    {% csrf_token %}
                    <input type="hidden" value="{{ product.id }}" class="prodt_id">
                    <h4 class="box-title mt-1">Product description</h4>
                    <p class="product-description">{{ product.description }}</p>
                    <h2 class="mt-5">
                        <small class="text-success">${{ product.price }}</small>
                    </h2>
                    <button type="button" class="addToCartBtn btn btn-primary btn-rounded">Add to cart</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="{% static 'main/js/cart.js' %}" type="text/javascript"></script>
{% endblock %}

templates/product/products.html
{% extends 'base.html' %}

{% block content %}
<h1>Products</h1>
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            {% if products %}
                {% for product in products %}
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="{{ product.image.url }}" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{ product.title }}</h5>
                                    <!-- Product price-->
                                    ${{ product.price }}
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'product:product_detail' prod_id=product.id %}">view product</a></div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <h5>No Content</h5>
            {% endif %}

        </div>
    </div>
</section>
{% endblock %}